export type Product = {
id: string;
name: string;
category: string;
categoryTag: string;
price: number;
rating: number;
reviewCount: number;
imageUrl: string;
};


export const mockProducts: Product[] = [
{
id: 'p1',
name: 'Phone Stand',
category: 'Accessories',
categoryTag: 'Other',
price: 29.9,
rating: 5.0,
reviewCount: 1200,
imageUrl: '/images/stand.jfif',
},
{
id: 'p2',
name: 'Detergent',
category: 'Audio',
categoryTag: 'Music',
price: 149.5,
rating: 4.8,
reviewCount: 540,
imageUrl: '/images/detergent.jfif',
},
{
id: 'p3',
name: 'fan',
category: 'Carry',
categoryTag: 'Other',
price: 39.0,
rating: 4.9,
reviewCount: 230,
imageUrl: '/images/fan.jfif',
},
{
id: 'p4',
name: 'fan',
category: 'Carry',
categoryTag: 'Other',
price: 39.0,
rating: 4.9,
reviewCount: 230,
imageUrl: '/images/fan.jfif',
},
{
id: 'p5',
name: 'Fan',
category: 'Carry',
categoryTag: 'Other',
price: 39.0,
rating: 4.9,
reviewCount: 230,
imageUrl: '/images/fan.jfif',
},
{
id: 'p6',
name: 'fan',
category: 'Carry',
categoryTag: 'Other',
price: 39.0,
rating: 4.9,
reviewCount: 230,
imageUrl: '/images/fan.jfif',
},
];

export interface Product_2 {
  id: number;
  name: string;
  price: string;
  imageUrl: string[]; // supports multiple for products like Carabiner Set
  isLimited: boolean;
  isFavorited: boolean;
  category?: string;
  categoryTag?: string;
}

export const mockProducts_2: Product_2[] = [
  {
    id: 1,
    name: "JaQ Bag",
    price: "$139.00",
    imageUrl: ["/images/jaq-bag.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Bags",
    categoryTag: "Travel",
  },
  {
    id: 2,
    name: "Nanga Sandal",
    price: "$89.00",
    imageUrl: ["/images/nanga-sandal.jpg"],
    isLimited: true,
    isFavorited: false,
    category: "Footwear",
    categoryTag: "Sandals",
  },
  {
    id: 3,
    name: "Carabiner Set",
    price: "$32.00",
    imageUrl: ["/images/carabiner-1.jpg", "/images/carabiner-2.jpg", "/images/carabiner-3.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Gear",
    categoryTag: "Climbing",
  },
  {
    id: 4,
    name: "P.S Cap",
    price: "$45.00",
    imageUrl: ["/images/ps-cap.jpg"],
    isLimited: true,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 5,
    name: "Trail Jacket",
    price: "$159.00",
    imageUrl: ["/images/trail-jacket.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Apparel",
    categoryTag: "Jackets",
  },
  {
    id: 6,
    name: "Peak Shorts",
    price: "$69.00",
    imageUrl: ["/images/peak-shorts.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Apparel",
    categoryTag: "Shorts",
  },
  {
    id: 7,
    name: "Summit Bottle",
    price: "$49.00",
    imageUrl: ["/images/summit-bottle.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Gear",
    categoryTag: "Hydration",
  },
  {
    id: 8,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 9,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 10,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 11,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 12,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 13,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 14,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 15,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 16,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 17,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 18,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 19,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 20,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 21,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 22,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
  {
    id: 23,
    name: "Beanie",
    price: "$39.00",
    imageUrl: ["/images/beanie.jpg"],
    isLimited: false,
    isFavorited: false,
    category: "Accessories",
    categoryTag: "Hats",
  },
];